### ISSUE TITLE
problems with 2.5

### ISSUE THREAD

**Issue by dsjiern** [bigbluebutton/docker#208]
Hello,

I tried the new Version 2.5 and I found following problems:

1. I hat do download the bbb-pads manually and copy it as subfolder to ./mods/bbb-pads/
2. Audio is working fine, but camera and screenshare are not working, when I open about:webrtc in Firefox, I get no external candidates:
<img width="1998" alt="grafik" src="https://user-images.githubusercontent.com/29799323/162091160-59bef2ea-0f94-41a4-b7a1-72b4bd08c80c.png">
<img width="850" alt="grafik" src="https://user-images.githubusercontent.com/29799323/162091346-8e6fedf9-99a4-4562-9baa-b834254ed816.png">
3. I always try the server with API Mate, when I create a new meeting, it show's a duplicate warning. Joining afterwards is working though.
<img width="664" alt="grafik" src="https://user-images.githubusercontent.com/29799323/162092165-fcb7f068-db92-41ed-afbb-9121e6be3fa5.png">

I tried it on my testing server, it doesn't have a IPv6-address, just a IPv4. Also with my TURN server it doesn't work.

greetings
dsjiern

**Comment by alangecker** [comment]
heyho :)

- regarding 1.: it's a submodule! after switching a branch you should always use `./scripts/upgrade` which also updates/clones the submodules
- regarding 2.: the `2.5.x` branch is heavily work in progress and no one ever said that it works :D the issue you mention is due to the current missing mediasoup support (one of the missings ticks in https://github.com/bigbluebutton/docker/pull/207). Let's rather have further discussion about the state of 2.5.x in the PR, instead of separate issues :)

**Comment by dsjiern** [comment]
Hey,

2: thank you, I didn't see this discussion :)

1: yes, I know that this is a submodule, but `/scripts/upgrade` doesn't fetch the bbb-pods.

**Comment by alangecker** [comment]
both should be fixed now in the `2.5.x` branch with the last commits ;)
