### ISSUE TITLE
Support for BigBlueButton v2.6

### ISSUE THREAD

**Issue by alangecker** [bigbluebutton/docker#245]
BBB 2.6 is on the way, but I have currently not really much capacity to take care about it.

Anyone up for looking into this task? 🙂 

#### steps
- Looking into the [changelog](https://github.com/bigbluebutton/bigbluebutton/releases) for anything, which requires a change of the docker setup to be applied.
  * especially changes labelled as "packaging and configuration" often requires a change to bbb-docker 
  * I've found already:
      - https://github.com/bigbluebutton/bigbluebutton/pull/12231
      - https://github.com/bigbluebutton/bigbluebutton/pull/15394
      - https://github.com/bigbluebutton/bigbluebutton/pull/15779
      - https://github.com/bigbluebutton/bigbluebutton/pull/15977
      - https://github.com/bigbluebutton/bigbluebutton/pull/15766
      - https://github.com/bigbluebutton/bigbluebutton/pull/15926
     
- adjusting everything accordingly
- creating a pull request
- feel free to ask questions!

**Comment by alangecker** [comment]
@lightweight I got now testable code #255 (should work with `git checkout v2.6 && ./scripts/upgrade-and-build && echo thanks for waiting so long && docker-compose up -d`),  if you are currently motivated, I would be happy if someone could test it 🙂

**Comment by Zoey2936** [comment]
I've didn't made a big test, but a conference and greenlight worked. I've didn't tested recording

**Comment by alangecker** [comment]
it seems to run so far and [bbb-docker Release 2.6.0](https://github.com/bigbluebutton/docker/pull/256) is upcoming. 

for any further errors please open a separate issue or comment in the PR as long as it is not merged :)

**Comment by alangecker** [comment]
@InforMedic all `chmod` commands in the dockerfiles are executed as root, so I can't understand why they would fail 🤔 
what folders and containers are we talking about?

**Comment by InforMedic** [comment]
It was related to the 2 conf definitions in the freeswitch service (`conf/sip_profiles`and `conf/dialplan_public`). There was a message saying that they coul not be mounted into the container (permission denied). I helped myself temporarly by uncommenting. Next build was a similar error related to the volume in the greenlight service (because the folder locally  doesnt exists). Creating it like i normally do with bind mounts didnt helped - now i received the message permission denied (like i had with freeswitch) . Then i chmod `greenlight-data` and the build went through.

Then checking everything again today, i see i forgot to re-uncomment the freeswitch volumes so i am able to quickly reproduce this topic without chmodding anything. But this time the build of freeswitch and everything else went through (what is good =). Re-checking the 998:988 on my filesystem -> the greenswitch-data folder is again my user permission?!? look like i never did what i wrote?! so i think we better forget about this topic. :)

**Comment by lightweight** [comment]
Apologies, @alangecker - got distracted by other things. Just trying to upgrade a recently deployed dockerised BBB on the latest v2.5 to v2.6... will report back. Many thanks for your hard work on this!

**Comment by lightweight** [comment]
Hah, great work @alangecker! Many thanks for you continued hard work. I finally got 2.6 going including the Greenlight upgrade, migration of recordings from a separate 2.5 instance, and got Coturn working with ENABLE_HTTPS_PROXY=false (so I could run other services on this same instance), although haven't figured out how to get it to allow generating 'video' versions of recordings (working on that now)... If I can help anyone else, let me know.
